---
title: "Ghana_PointPattern_Analysis"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Import packages

```{r}
library(pacman)


pacman::p_load(tidyverse,  
               sf,        
               spatstat,  
               sparr,      
               raster,     
               readxl,
               ggplot2,
               spatstat,  
               viridis,
               ggspatial)  
```

## Import Data
```{r results='hide'}
# shapefile

ghana_map <- st_read(
  "../Shapefiles/261_Districts.shp") %>% 
  st_make_valid() %>% 
  filter(!is.na(OBJECTID))

# pull in case data
cases <- readxl::read_xlsx("GH_YF_cases.xlsx")
```

## Reproject spatial objects 
```{r results='hide'}
# convert case data to sf object 
cases_sf <- st_as_sf(cases, coords = c("x", "y"), crs = 4326)

# convert shapefile to correct crs for meters
ghana_sf <- st_transform(ghana_map, crs = 32630)

# now match crs of case data to shapefile
cases_sf <- st_transform(cases_sf, crs = st_crs(ghana_sf))


# verify matching crs projections
st_crs(cases_sf)
st_crs(ghana_sf)

# check bounding boxes to make sure units are correct
# Bounding boxes
st_bbox(cases_sf)    # points in UTM meters
st_bbox(ghana_sf)  # polygon in UTM meters
```

## Create study window and ppp object
```{r warning=FALSE}
# create definition for the study region
ghana_owin <- as.owin(ghana_sf)

# make a ppp object for case data
cases_ppp <- ppp(
  x = st_coordinates(cases_sf)[, 1],  # all X coordinates
  y = st_coordinates(cases_sf)[, 2],  # all Y coordinates
  window = ghana_owin            # study area
)

# check study window
plot(ghana_owin)
points(cases_ppp$x, cases_ppp$y, pch = 16, cex = 0.5)
```

## Ripley's K/L Plots with MC envelope - Humans
```{r eval= FALSE}
# produce k-function with envelope (MC simulations)
   # Envelope function
kf.env <- envelope(cases_ppp, Kest, nsim = 999, correction="isotropic")

saveRDS(kf.env, "Results/kf_humans_999sim.rds")

```

```{r include=FALSE}
 kf.env <- readRDS("Results/kf_humans_999sim.rds")
```

```{r}
  # Plot K function for human cases
 plot(kf.env,main = NULL,
      legendargs = list(x = "topleft", inset = c(0.0, 0), cex = 0.7))
```

## K function - Humans
```{r K_function_humans, include=FALSE}
 dir.create("Results", showWarnings = FALSE)

# Open TIFF device
 tiff(filename = "Results/K_plot_human_cases.tiff",
      width = 180, height = 120, units = "mm", res = 300, compression = "lzw")

# Plot K function for human cases
 plot(kf.env,main = NULL,
      legendargs = list(x = "topleft", inset = c(0.0, 0), cex = 0.7))

 dev.off()

 # observed curve is above the CSR and envelope, providing strong evidence of clustering
```




```{r include=FALSE}
 dir.create("Results", showWarnings = FALSE)

 pdf(
   file = "Results/K_plot_human_cases.pdf",
   width = 180/25.4,   # mm to inches
   height = 120/25.4
 )

# plot K function for human cases
 plot(kf.env,main = NULL,
      legendargs = list(x = "topleft", inset = c(0.0, 0), cex = 0.7))

 dev.off()
```



## L function for human cases
```{r eval = FALSE}
# produce L-function with envelope
# Envelope function
lf.env <- envelope(cases_ppp, Lest, nsim = 999, correction="isotropic")

# Center it by subtracting r
lf.env$obs <- lf.env$obs - lf.env$r
lf.env$lo  <- lf.env$lo  - lf.env$r
lf.env$hi  <- lf.env$hi  - lf.env$r
lf.env$theo <- 0  # theoretical CSR line at 0

# saveRDS(lf.env, "Results/lf_humans_999sim.rds")

```

```{r include=FALSE}
lf.env <- readRDS("Results/lf_humans_999sim.rds")
```

```{r}
# Plot the centered version
plot(lf.env, main = NULL,
     legendargs = list(x = "topright", inset = c(0.0, 0), cex = 0.7))

```

```{r}
dir.create("Results", showWarnings = FALSE)

# Open TIFF device
tiff(filename = "Results/L_plot_human_cases.tiff",
     width = 180, height = 120, units = "mm", res = 300, compression = "lzw")

# Plot the centered version
plot(lf.env, main = NULL,
     legendargs = list(x = "topright", inset = c(0.0, 0), cex = 0.7))

dev.off()
# observed line is above the CSR and envelope, providing strong evidence of clustering

```

```{r}
dir.create("Results", showWarnings = FALSE)

pdf(
  file = "Results/L_plot_human_cases.pdf",
  width = 180/25.4,  ## mm to inches
  height = 120/25.4
)

# Plot the centered version
plot(lf.env, main = NULL,
     legendargs = list(x = "topleft", inset = c(0.0, 0), cex = 0.7))

dev.off()
```

## Find peak distance as a candidate for bandwidth
```{r}
# L(r) - r from observed curve
L_diff <- lf.env$obs

# find distance of strongest clustering
peak_idx <- which.max(L_diff)
dist_peak <- lf.env$r[peak_idx]

dist_peak

# at 30155.51 points are most strongly clustered compared to CSR
 # Use as candidate bandwidth in plots
```


## KDE Plot with human case kernel density bandwidth
```{r kernel_density_plot_humans}

#  Kernel density (sigma is in meters in this CRS)
sigma_val <-   25000 # ~ peak r from Ripley's K/L, slightly less to account for variation and oversmoothing

# increased dimensions to smooth edges in final KDE plot
dens <- density.ppp(cases_ppp, sigma = sigma_val, at = "pixels", edge = TRUE, 
                    dimyx = c(500, 500))

#  Convert to data frame for ggplot
dens_df <- as.data.frame(as.im(dens))
names(dens_df) <- c("x", "y", "density")

# remove vereda borders from shapefile 
ghana_union <- st_union(ghana_sf)

kd_plot_humans2 <- ggplot() +
  # Raster / density layer
  geom_tile(data = dens_df, aes(x = x, y = y, fill = density)) +
  scale_fill_viridis(name = "Case density", option = "viridis") +
  
  # Shapefile polygon outlines
  geom_sf(data = ghana_union, fill = NA, linewidth = 0.2) +
  
  # Human cases (blue)
  geom_sf(
    data = cases_sf,
    aes(color = "Human cases"),
    shape = 16, size = 1
  ) +
  
  # Labels
  labs(
    color = "Points"
  ) +
  
  # Colorblind-safe colors
  scale_color_manual(
    values = c(
      "Human cases" = "orange"
    )
  ) +
  theme_minimal(base_size = 10) +
theme(
  axis.title = element_blank(),
  axis.text  = element_blank(),
  axis.ticks = element_blank(),
  panel.grid = element_blank()
) +
  annotation_scale(
    location   = "bl",
    width_hint = 0.25,
    text_cex   = 0.55,
    line_width = 0.6,
    pad_x      = unit(0.5, "npc"),
    pad_y      = unit(0.03, "npc")
  ) +
annotation_north_arrow(
  location = "br",
  which_north = "true",
  height = unit(0.8, "cm"),
  width  = unit(0.8, "cm"),
  pad_x  = unit(0.02, "npc"),
  pad_y  = unit(0.02, "npc"),
  style = north_arrow_fancy_orienteering()
)

kd_plot_humans2

```



```{r}
ggsave(
filename = file.path("Results", "kd_plot_humans.tiff"),
plot = kd_plot_humans2,
device = "tiff",
dpi = 300,
width = 180,
height = 120,
units = "mm",
compression = "lzw"
)
```
